<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <distributionManagement>
        <snapshotRepository>
            <id>artifact-registry</id>
            <url>artifactregistry://us-central1-maven.pkg.dev/prodoscore-artifactory/prodoscore-java-libraries</url>
        </snapshotRepository>
        <repository>
            <id>artifact-registry</id>
            <url>artifactregistry://us-central1-maven.pkg.dev/prodoscore-artifactory/prodoscore-java-libraries</url>
        </repository>
    </distributionManagement>

    <repositories>
        <repository>
            <id>artifact-registry</id>
            <url>artifactregistry://us-central1-maven.pkg.dev/prodoscore-artifactory/prodoscore-java-libraries</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <groupId>com.prodoscore</groupId>
    <artifactId>ProdoscoreWebsiteUIAutomation</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>ProdoscoreWebsiteUIAutomation</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>18</maven.compiler.source>
        <maven.compiler.target>18</maven.compiler.target>
        <maven-compiler-plugin-version>3.11.0</maven-compiler-plugin-version>
        <encoding-version>UTF-8</encoding-version>
        <codimite-framework-version>0.0.21.1</codimite-framework-version>
        <maven-surefire-plugin-version>3.2.1</maven-surefire-plugin-version>
        <google.api-client-version>2.0.0</google.api-client-version>
        <google-api-services-sheets-version>v4-rev20220927-2.0.0</google-api-services-sheets-version>
        <google-auth-library-oauth2-http-version>1.22.0</google-auth-library-oauth2-http-version>
        <defaultSuiteFile>AllTestSuite.xml</defaultSuiteFile>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.codimite.framework</groupId>
            <artifactId>FrameworkUI</artifactId>
            <version>${codimite-framework-version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>${google.api-client-version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-sheets</artifactId>
            <version>${google-api-services-sheets-version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.auth</groupId>
            <artifactId>google-auth-library-oauth2-http</artifactId>
            <version>${google-auth-library-oauth2-http-version}</version>
        </dependency>
    </dependencies>

    <build>
        <extensions>
            <extension>
                <groupId>com.google.cloud.artifactregistry</groupId>
                <artifactId>artifactregistry-maven-wagon</artifactId>
                <version>2.2.0</version>
            </extension>
        </extensions>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin-version}</version>
                <configuration>
                    <encoding>${encoding-version}</encoding>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin-version}</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/test/resources/testng/${defaultSuiteFile}</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
